/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_login (void);
GtkWidget* create_windowGestion_Capteur (void);
GtkWidget* create_employe (void);
GtkWidget* create_windowAjouterCap (void);
GtkWidget* create_dialogAjoutSucc (void);
GtkWidget* create_windowConfirmSupp (void);
GtkWidget* create_liste_clients_particuliers (void);
GtkWidget* create_ajouter_client_entreprise_ (void);
GtkWidget* create_menu (void);
GtkWidget* create_Attention (void);
GtkWidget* create_modifier_client_entreprise_ (void);
GtkWidget* create_modification_client_particulier (void);
GtkWidget* create_liste_clients_professionnels (void);
GtkWidget* create_operationReussie (void);
GtkWidget* create_operationNonReussie (void);
GtkWidget* create_Menu (void);
GtkWidget* create_ADMIN (void);
GtkWidget* create_GT_Employe2 (void);
GtkWidget* create_GT_Employe1 (void);
GtkWidget* create_GT_OperationE (void);
GtkWidget* create_GT_OperationR (void);
GtkWidget* create_GT_AS (void);
GtkWidget* create_GT_Employe3 (void);
GtkWidget* create_windowSMS (void);
GtkWidget* create_window2 (void);
GtkWidget* create_ajout_client_individuel (void);
GtkWidget* create_supprimerClientInd (void);
GtkWidget* create_SupprimerClientPro (void);
GtkWidget* create_Nombre_de_troupeaux_de_chaque_type (void);
GtkWidget* create_liste_des_troupeaux (void);
GtkWidget* create_Ouvrier_de_lannee (void);
GtkWidget* create_bestouv (void);
GtkWidget* create_GT_Admin (void);
