/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  GtkWidget *login;
  GtkWidget *windowGestion_Capteur;
  GtkWidget *employe;
  GtkWidget *windowAjouterCap;
  GtkWidget *dialogAjoutSucc;
  GtkWidget *windowConfirmSupp;
  GtkWidget *liste_clients_particuliers;
  GtkWidget *ajouter_client_entreprise_;
  GtkWidget *menu;
  GtkWidget *Attention;
  GtkWidget *modifier_client_entreprise_;
  GtkWidget *modification_client_particulier;
  GtkWidget *liste_clients_professionnels;
  GtkWidget *operationReussie;
  GtkWidget *operationNonReussie;
  GtkWidget *Menu;
  GtkWidget *ADMIN;
  GtkWidget *GT_Employe2;
  GtkWidget *GT_Employe1;
  GtkWidget *GT_OperationE;
  GtkWidget *GT_OperationR;
  GtkWidget *GT_AS;
  GtkWidget *GT_Employe3;
  GtkWidget *windowSMS;
  GtkWidget *window2;
  GtkWidget *ajout_client_individuel;
  GtkWidget *supprimerClientInd;
  GtkWidget *SupprimerClientPro;
  GtkWidget *page ;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  gtk_widget_show (window1);
 /* login = create_login ();
  gtk_widget_show (login);
  windowGestion_Capteur = create_windowGestion_Capteur ();
  gtk_widget_show (windowGestion_Capteur);  */
 // employe = create_employe ();
//  gtk_widget_show (employe);
/*  windowAjouterCap = create_windowAjouterCap ();
  gtk_widget_show (windowAjouterCap);
  dialogAjoutSucc = create_dialogAjoutSucc ();
  gtk_widget_show (dialogAjoutSucc);
  windowConfirmSupp = create_windowConfirmSupp ();
  gtk_widget_show (windowConfirmSupp);
  liste_clients_particuliers = create_liste_clients_particuliers ();
  gtk_widget_show (liste_clients_particuliers);
  ajouter_client_entreprise_ = create_ajouter_client_entreprise_ ();
  gtk_widget_show (ajouter_client_entreprise_);   */
 // menu = create_menu ();
 // gtk_widget_show (menu);
/*  Attention = create_Attention ();
  gtk_widget_show (Attention);
  modifier_client_entreprise_ = create_modifier_client_entreprise_ ();
  gtk_widget_show (modifier_client_entreprise_);
  modification_client_particulier = create_modification_client_particulier ();
  gtk_widget_show (modification_client_particulier);
  liste_clients_professionnels = create_liste_clients_professionnels ();
  gtk_widget_show (liste_clients_professionnels);
  operationReussie = create_operationReussie ();
  gtk_widget_show (operationReussie);
  operationNonReussie = create_operationNonReussie ();
  gtk_widget_show (operationNonReussie);
  Menu = create_Menu ();
  gtk_widget_show (Menu);  */
//  ADMIN = create_ADMIN ();
 // gtk_widget_show (ADMIN);
/*  GT_Employe2 = create_GT_Employe2 ();
  gtk_widget_show (GT_Employe2);
  GT_Employe1 = create_GT_Employe1 ();
  gtk_widget_show (GT_Employe1);
  GT_OperationE = create_GT_OperationE ();
  gtk_widget_show (GT_OperationE);
  GT_OperationR = create_GT_OperationR ();
  gtk_widget_show (GT_OperationR);
  GT_AS = create_GT_AS ();
  gtk_widget_show (GT_AS);
  GT_Employe3 = create_GT_Employe3 ();
  gtk_widget_show (GT_Employe3); */
 // windowSMS = create_windowSMS ();
//  gtk_widget_show (windowSMS); 
 // window2 = create_window2 ();
//  gtk_widget_show (window2);
/*  ajout_client_individuel = create_ajout_client_individuel ();
  gtk_widget_show (ajout_client_individuel);
  supprimerClientInd = create_supprimerClientInd ();
  gtk_widget_show (supprimerClientInd);
  SupprimerClientPro = create_SupprimerClientPro ();
  gtk_widget_show (SupprimerClientPro);    */
  // page = create_Nombre_de_troupeaux_de_chaque_type();
 // gtk_widget_show(page);

  gtk_main ();
  return 0;
}

